[package]
name = "protos"
version = "0.1.0"
edition = "2021"

[features]
default = ["proto_full"]
proto_full = ["authentication", "message"]
"authentication" = []
"message" = []

[dependencies]
bytes = "1.1.0"
prost = "0.12"
pbjson = "0.6"
pbjson-types = "0.6"
serde = "1.0"
tonic = { version = "0.11", features = ["gzip"] }