version: "3.7"

services:
  authdb:
    image: postgres
    container_name: authdb
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/data/postgres
volumes:
  pgdata:
    driver: local
